-- MySQL Script generated by MySQL Workbench
-- Fri Mar 22 11:44:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Cliente` (
  `Cod_Cliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobre_Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Data_Nascimento` DATE NOT NULL,
  PRIMARY KEY (`Cod_Cliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Fornecedor` (
  `Cod_Fornecedor` INT NOT NULL,
  `Razão_Social` VARCHAR(45) NOT NULL,
  `CNPJ/CPF` VARCHAR(45) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Status` TINYINT NOT NULL,
  PRIMARY KEY (`Cod_Fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto` (
  `Cod_Produto` INT NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  `Descrição` VARCHAR(100) NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `Cod_Fornecedor` INT NOT NULL,
  PRIMARY KEY (`Cod_Produto`),
  INDEX `Cod_Fornecedor_idx` (`Cod_Fornecedor` ASC) VISIBLE,
  CONSTRAINT `Cod_Fornecedor`
    FOREIGN KEY (`Cod_Fornecedor`)
    REFERENCES `ecommerce`.`Fornecedor` (`Cod_Fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Pedido` (
  `Cod_Pedido` INT NOT NULL,
  `Status_pedido` VARCHAR(45) NOT NULL,
  `Data_pedido` DATETIME NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Cliente_CodCliente` INT NOT NULL,
  `Cod_produto` INT NOT NULL,
  PRIMARY KEY (`Cod_Pedido`, `Cliente_CodCliente`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_CodCliente` ASC) VISIBLE,
  INDEX `Cod_produto_idx` (`Cod_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_CodCliente`)
    REFERENCES `ecommerce`.`Cliente` (`Cod_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cod_produto`
    FOREIGN KEY (`Cod_produto`)
    REFERENCES `ecommerce`.`Produto` (`Cod_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Estoque` (
  `Cod_Estoque` INT NOT NULL,
  `Local` VARCHAR(45) NULL,
  `Qtd_total` INT NOT NULL,
  PRIMARY KEY (`Cod_Estoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_Estoque` (
  `Produto_CodProduto` INT NOT NULL,
  `Estoque_CodEstoque` INT NOT NULL,
  `Qtd_disponivel` INT NOT NULL,
  PRIMARY KEY (`Produto_CodProduto`, `Estoque_CodEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_CodEstoque` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_CodProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_CodProduto`)
    REFERENCES `ecommerce`.`Produto` (`Cod_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_CodEstoque`)
    REFERENCES `ecommerce`.`Estoque` (`Cod_Estoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Tipo_de_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Tipo_de_pagamento` (
  `Cod_Tipo_de_pagamento` INT NOT NULL,
  `Metodo_de_Pagamento` VARCHAR(45) NOT NULL,
  `Numero_de_parcelas` VARCHAR(45) NULL,
  `cod_pedido` INT NOT NULL,
  PRIMARY KEY (`Cod_Tipo_de_pagamento`),
  INDEX `cod_pedido_idx` (`cod_pedido` ASC) VISIBLE,
  CONSTRAINT `cod_pedido`
    FOREIGN KEY (`cod_pedido`)
    REFERENCES `ecommerce`.`Pedido` (`Cod_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Relação_Produto_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Relação_Produto_Pedido` (
  `Pedido_CodPedido` INT NOT NULL,
  `Pedido_Tipo_pagto_CodTipo_pagto` INT NOT NULL,
  `Produto_CodProduto` INT NULL,
  PRIMARY KEY (`Pedido_CodPedido`, `Pedido_Tipo_pagto_CodTipo_pagto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_CodProduto` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`Pedido_CodPedido` ASC, `Pedido_Tipo_pagto_CodTipo_pagto` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`Pedido_CodPedido`)
    REFERENCES `ecommerce`.`Pedido` (`Cod_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_CodProduto`)
    REFERENCES `ecommerce`.`Produto` (`Cod_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Transportador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Transportador` (
  `Cod_Transportador` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Custo_Frete` FLOAT NOT NULL,
  `Contato` VARCHAR(45) NULL,
  `Tempo_de_entrega_estimado` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Transportador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Entrega` (
  `Cod_Entrega` INT NOT NULL,
  `Data_entrega` DATETIME NOT NULL,
  `Status_entrega` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Cod_rastreio` VARCHAR(45) NOT NULL,
  `Pedido_Cod_Pedido` INT NOT NULL,
  `Transportador_Cod_Transportador` INT NOT NULL,
  PRIMARY KEY (`Cod_Entrega`, `Pedido_Cod_Pedido`, `Transportador_Cod_Transportador`),
  INDEX `fk_Entrega_Pedido1_idx` (`Pedido_Cod_Pedido` ASC) VISIBLE,
  INDEX `fk_Entrega_Transportador1_idx` (`Transportador_Cod_Transportador` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_Pedido1`
    FOREIGN KEY (`Pedido_Cod_Pedido`)
    REFERENCES `ecommerce`.`Pedido` (`Cod_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_Transportador1`
    FOREIGN KEY (`Transportador_Cod_Transportador`)
    REFERENCES `ecommerce`.`Transportador` (`Cod_Transportador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Detalhes_do_cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Detalhes_do_cartao` (
  `CodDetalhes_do_cartao` INT NOT NULL,
  `Numero_do_cartao` VARCHAR(45) NOT NULL,
  `Data_de_validade` VARCHAR(45) NOT NULL,
  `Tipo_de_pagamento_Cod_Tipo_de_pagamento` INT NOT NULL,
  `Nome_do_titular` VARCHAR(45) NOT NULL,
  `CPF_do_titular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodDetalhes_do_cartao`, `Tipo_de_pagamento_Cod_Tipo_de_pagamento`),
  INDEX `fk_Detalhes_do_cartao_Tipo_de_pagamento1_idx` (`Tipo_de_pagamento_Cod_Tipo_de_pagamento` ASC) VISIBLE,
  UNIQUE INDEX `Numero_do_cartao_UNIQUE` (`Numero_do_cartao` ASC) VISIBLE,
  CONSTRAINT `fk_Detalhes_do_cartao_Tipo_de_pagamento1`
    FOREIGN KEY (`Tipo_de_pagamento_Cod_Tipo_de_pagamento`)
    REFERENCES `ecommerce`.`Tipo_de_pagamento` (`Cod_Tipo_de_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Relacao_Tipo_de_pagamento_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Relacao_Tipo_de_pagamento_Pedido` (
  `Tipo_de_pagamento_Cod_Tipo_de_pagamento` INT NOT NULL,
  `Pedido_Cod_Pedido` INT NOT NULL,
  `Pedido_Cliente_CodCliente` INT NOT NULL,
  PRIMARY KEY (`Tipo_de_pagamento_Cod_Tipo_de_pagamento`, `Pedido_Cod_Pedido`, `Pedido_Cliente_CodCliente`),
  INDEX `fk_Tipo_de_pagamento_has_Pedido_Pedido1_idx` (`Pedido_Cod_Pedido` ASC, `Pedido_Cliente_CodCliente` ASC) VISIBLE,
  INDEX `fk_Tipo_de_pagamento_has_Pedido_Tipo_de_pagamento1_idx` (`Tipo_de_pagamento_Cod_Tipo_de_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Tipo_de_pagamento_has_Pedido_Tipo_de_pagamento1`
    FOREIGN KEY (`Tipo_de_pagamento_Cod_Tipo_de_pagamento`)
    REFERENCES `ecommerce`.`Tipo_de_pagamento` (`Cod_Tipo_de_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tipo_de_pagamento_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_Cod_Pedido` , `Pedido_Cliente_CodCliente`)
    REFERENCES `ecommerce`.`Pedido` (`Cod_Pedido` , `Cliente_CodCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Relacao_Fornecedor_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Relacao_Fornecedor_Produto` (
  `Fornecedor_Cod_Fornecedor` INT NOT NULL,
  `Produto_Cod_Produto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_Cod_Fornecedor`, `Produto_Cod_Produto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_Cod_Produto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor1_idx` (`Fornecedor_Cod_Fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_Cod_Fornecedor`)
    REFERENCES `ecommerce`.`Fornecedor` (`Cod_Fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_Cod_Produto`)
    REFERENCES `ecommerce`.`Produto` (`Cod_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
